config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  get "/about" => "public/homes#about"

  #管理者用
  #URL/admin/sign_in
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    get "/" => "homes#top"
    patch "/admin/order_details/:id" => "order_details#update", as: "order_details"
  end

  #顧客用
  #URL/customers/sign_in
  scope module: :public do
    resource :customers, only: [:show, :edit, :update]
    delete "/cart_items/empty" => "cart_items#empty", as: "empty"
    post "orders/confirm" => "orders#confirm", as: "confirm"
    get "orders/complete" => "orders#complete",as: "complete"
    get "/customers/unsubscribe" => "customers#unsubscribe", as: "unsubscribe"
    patch "/customers/withdrawal" => "customers#withdrawal", as: "withdrawal"
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :create, :index, :show]
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
    "〒" + postal_code + '' + address + '' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

   #小計
  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders

  def name
    self.last_name + "" + self.first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_detaios, dependent: :destroy

  def get_image
    image
  end
     #税込価格
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {
    credit: 0,
    bank: 1,
  }

  enum status: {
    payment_waiting: 0,
    payment_confirmation: 1,
    in_production: 2,
    preparing_delivery: 3,
    delivered: 4,
  }

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  def postage
    800
  end

  def with_tax_price
    (price * 1.1).floor
  end

  def subtotal
    item.with_tax_price * amount
  end


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum production_status: {
    no_production: 0,
    production_waiting: 1,
    in_production: 2,
    completed: 3,
  }

  belongs_to :order
  belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :pstal_code, :address, :telephone_number, :email, :is_active)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre =  Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
    @item_sum = 0
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    @item.save
    p @item.errors.full_messages
    redirect_to admin_item_path(@item.id)
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
    @genre = @item.genre
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @genres = Genre.all
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row m-5">
    <div class="col">
      <h2><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>会員ID</p>
    </div>
    <div class="col-4">
      <%= @customer.id %>
    </div>
  </div>

  <%= form_with model: @customer, url: admin_customer_path, method: :patch do |f| %>
  <div class="row">
    <div class="col-3">
      <p>氏名</p>
    </div>
    <div class="col-4">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
    <div class="col-4">
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>フリガナ</p>
    </div>
    <div class="col-4">
      <%= f.text_field :last_name_kana, class: "form-control" %>
    </div>
    <div class="col-4">
      <%= f.text_field :first_name_kana, class: "form-control" %>
    </div>
  </div>

   <div class="row">
    <div class="col-3">
      <p>郵便番号</p>
    </div>
    <div class="col-4">
      <%= f.text_field :postal_code, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>住所</p>
    </div>
    <div class="col-8">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>電話番号</p>
    </div>
    <div class="col-4">
      <%= f.telephone_field :telephone_number, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>メールアドレス</p>
    </div>
    <div class="col-4">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>会員ステータス</p>
    </div>
    <div class="col-2">
      <label><%= f.radio_button :is_active, true %>有効</label>
    </div>
    <div class="col-2">
      <label><%= f.radio_button :is_active, false %>退会</label>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-3"></div>
    <div class="col-6">
      <%= f.submit "変更を保存", class: "btn btn-success" %>
    </div>
  </div>

  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row m-5">
    <div class="col">
      <h2>会員一覧</h2>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <table class="table">
        <thead class="table-secondary">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to customer.name, admin_customer_path(customer.id) %></td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_active %>
                <p class="text-success">有効</p>
              <% else %>
                <p class="text-muted">退会</p>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row m-5">
    <div class="col">
      <h2><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>会員ID</p>
    </div>
    <div class="col-4">
      <%= @customer.id %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>氏名</p>
    </div>
    <div class="col-4">
      <%= @customer.last_name %><%= @customer.first_name %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>フリガナ</p>
    </div>
    <div class="col-4">
      <%= @customer.last_name_kana %><%= @customer.first_name_kana %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>郵便番号</p>
    </div>
    <div class="col-4">
      <%= @customer.postal_code %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>住所</p>
    </div>
    <div class="col-4">
      <%= @customer.address %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>電話番号</p>
    </div>
    <div class="col-4">
      <%= @customer.telephone_number %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>メールアドレス</p>
    </div>
    <div class="col-4">
      <%= @customer.email %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>会員ステータス</p>
    </div>
    <div class="col-4">
      <% if @customer.is_active %>
        <p class="text-success">有効</p>
      <% else %>
       <p class="text-muted">退会</p>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-3"></div>
    <div class="col-4">
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success" %>
    </div>
    <div class="col-4">
      <%= link_to "注文履歴一覧を見る", admin_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>