config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  get "/about" => "public/homes#about"

  #管理者用
  #URL/admin/sign_in
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    get "/" => "homes#top"
    patch "/admin/order_details/:id" => "order_details#update", as: "order_details"
  end

  #顧客用
  #URL/customers/sign_in
  scope module: :public do
    resource :customers, only: [:show, :edit, :update]
    delete "/cart_items/empty" => "cart_items#empty", as: "empty"
    post "orders/confirm" => "orders#confirm", as: "confirm"
    get "orders/complete" => "orders#complete",as: "complete"
    get "/customers/unsubscribe" => "customers#unsubscribe", as: "unsubscribe"
    patch "/customers/withdrawal" => "customers#withdrawal", as: "withdrawal"
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :create, :index, :show]
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
    "〒" + postal_code + '' + address + '' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

   #小計
  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders

  def name
    self.last_name + "" + self.first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_detaios, dependent: :destroy

  def get_image
    image
  end
     #税込価格
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {
    credit: 0,
    bank: 1,
  }

  enum status: {
    payment_waiting: 0,
    payment_confirmation: 1,
    in_production: 2,
    preparing_delivery: 3,
    delivered: 4,
  }

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  def postage
    800
  end

  def with_tax_price
    (price * 1.1).floor
  end

  def subtotal
    item.with_tax_price * amount
  end


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum production_status: {
    no_production: 0,
    production_waiting: 1,
    in_production: 2,
    completed: 3,
  }

  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre =  Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
    @item_sum = 0
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    @item.save
    p @item.errors.full_messages
    redirect_to admin_item_path(@item.id)
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
    @genre = @item.genre
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @genres = Genre.all
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order_detail = OrderDetail
    @customer = @order.customer
    @sum = 0
    @name = @customer.last_name + @customer.first_name
  end

  def update
  end

  private

  def order_params
    params.require(:order).permit(:payment_method, :address, :postal_code, :name, :postage, :total_payment, :customer_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">
      <h2>ジャンル編集</h2>
    </div>
  </div>

  <%= form_with model: @genre, url: admin_genre_path(@genre), method: :patch do |f| %>
  <div class="row m-3">
    <div class="col-2">
      <p><strong>ジャンル名</strong></p>
    </div>
    <div class="col">
      <%= f.text_field :name, class: "form-control m-4" %>
    </div>
    <div class="col">
      <%= f.submit "変更を保存", class: "btn btn-success m-4" %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/genres/index.html.erb
<!--ジャンルの新規登録-->
<div class="container">
  <div class="row mt-5">
    <div class="col">
      <h2 class="d-inline-flex p-2 bd-light">ジャンル一覧・追加</h2>
    </div>
  </div>

  <div class="row align-items-start">
    <div class="col-6">
      <table>
        <thead>
        <%= form_with model: @genre, url: "/admin/genres", method: :post do |f| %>
          <tr>
            <th>ジャンル名</th>
            <td></td>
            <th><%= f.text_field :name, placeholder: "ジャンル名", class: "form-control m-5" %></th>
            <td></td>
            <th><%= f.submit "新規投稿", class: "btn btn-success m-3" %></th>
          </tr>
        <% end %>
        </thead>
      </table>
    </div>
  </div>
</div>

<!--ジャンル一覧、編集ページに進むボタン-->
<div class="container">
  <div class="row align-items-start">
    <div class="col-5">
      <table class="table">
        <thead class="table-secondary">
          <tr>
            <td></td>
            <td>ジャンル</td>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td></td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
          </tr>
          <% end %>
        </tbody>
     </table>
    </div>
  </div>
</div>

app/views/admin/homes/top.html.erb
<div class="container mt-5">
  <h2>注文履歴一覧</h2>
  <div class="row">
    <div class="col">
      <table class="table">
        <thead class="table-secondary">
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
          <tr>
            <td><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M'), admin_order_path(order.id) %></td>
            <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
            <td><%= order.order_details.sum(:amount) %></td>
            <td><%= order.status_i18n %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row m-5">
    <div class="col">
      <h2>商品編集</h2>
    </div>
  </div>

  <%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>
  <div class="row">
    <div class="col-3">
      <p>商品画像</p>
    </div>
    <div class="col-4">
      <%= f.file_field :image, accept: "image/*" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>商品名</p>
    </div>
    <div class="col-4">
      <%= f.text_field :name, class: "from-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>商品説明</p>
    </div>
    <div class="col-4">
      <%= f.text_area :introduction, class: "from-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>ジャンル</p>
    </div>
    <div class="col-4">
      <%= f.collection_select(:genre_id, @genres, :id, :name, prompt: "--選択してください--") %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>税抜価格</p>
    </div>
    <div class="col-4">
      <%= f.text_field :price, class: "from-control" %>
    </div>
    <div class="col-2">
      <p>円</p>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>販売ステータス</p>
    </div>
    <div class="col-2">
      <label><%= f.radio_button :is_active, true %>販売中</label>
    </div>
    <div class="col-2">
      <label><%= f.radio_button :is_active, false %>販売停止中</label>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-3"></div>
    <div class="col-3">
      <p><%= f.submit "変更を保存", class: "btn btn-success" %></p>
    </div>
  </div>

  <% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row m-5">
    <div class="col">
      <h2>商品一覧</h2>
    </div>
    <div class="col">
      <%= link_to "新規登録", new_admin_item_path, class: "btn btn-success" %>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <table class="table">
        <thead class="table-secondary">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name, admin_item_path(item.id) %></td>
            <td><%= item.price %></td>
            <td><%= item.genre.name %></td>
            <td>
              <% if item.is_active %>
                <div class="text-success">販売中</div>
              <% else %>
                <div class="text-secondary">販売停止中</div>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row m-5">
    <div class="col">
      <h2>商品新規登録</h2>
    </div>
  </div>

  <%= form_with model: @item, url: "/admin/items", method: :post do |f| %>
  <div class="row">
    <div class="col-3">
      <p>商品画像</p>
    </div>
    <div class="col-4">
      <%= f.file_field :image, accept: "image/*" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>商品名</p>
    </div>
    <div class="col-4">
      <%= f.text_field :name, placeholder: "商品名", class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>商品説明</p>
    </div>
    <div class="col-4">
      <%= f.text_area :introduction, placeholder: "ここに説明文を記述します", class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>ジャンル</p>
    </div>
    <div class="col-4">
      <%= f.collection_select(:genre_id, @genres, :id, :name, prompt: "--選択してください--") %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>税抜価格</p>
    </div>
    <div class="col-4">
      <%= f.text_field :price, placeholder: "1000", class: "form-control" %>
    </div>
    <div class="col-2">
      <p>円</p>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>販売ステータス</p>
    </div>
    <div class="col-2">
      <label><%= f.radio_button :is_active, true %>販売中</label>
    </div>
    <div class="col-2">
      <label><%= f.radio_button :is_active, false %>販売停止中</label>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-3"></div>
    <div class="col-3">
      <p><%= f.submit "新規登録" ,class: "btn btn-success" %></p>
    </div>
  </div>

  <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h2 class="bg-light m-4">商品詳細</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-4">
      <%= image_tag @item.get_image, size: "320x180", class: "m-5" %>
    </div>

    <div class="col-6 m-5">
      <table>
        <thead class="mt-5">
          <tr class="m-2">
            <td>商品名</td>
            <td><%= @item.name %></td>
          </tr>
          <tr class="m-2">
            <td>商品説明</td>
            <td><%= @item.introduction %></td>
          </tr>
          <tr class="m-2">
            <td>ジャンル</td>
            <td><%= @genre.name %></td>
          </tr>
          <tr class="m-2">
            <td>
              税込価格<br/>
              (税抜価格)
            </td>
            <td><%= (@item.price * 1.1).floor %>(<%= @item.price %>)円</td>
          </tr>
          <tr class="m-2">
            <td>販売ステータス</td>
            <td>
              <% if @item.is_active %>
                <div class="text-success">販売中</div>
              <% else %>
                <div class="text-secondary">販売停止中</div>
              <% end %>
            </td>
          </tr>
        </thead>
      </table>
      <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success" %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">

  <div class="row m-5">
    <div class="col">
      <h2>注文履歴詳細</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p><strong>購入者</strong></p>
    </div>
    <div class="col-4">
      <%= link_to @name, admin_customer_path(@customer.id) %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p><strong>注文日</strong></p>
    </div>
    <div class="col-4">
      <%= @order.created_at.strftime('%Y/%m/%d') %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p><strong>配送先</strong></p>
    </div>
    <div class="col-4">
      〒<%= @order.postal_code %><%= @order.address %><br>
      <%= @order.name %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p><strong>支払方法</strong></p>
    </div>
    <div class="col-4">
      <%= @order.payment_method_i18n %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p><strong>注文ステータス</strong></p>
    </div>
    <div class="col-4">
      <%= @order.status_i18n %>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-8">
      <table class="table">
        <thead class="table-secondary">
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</td>
            <td>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= (order_detail.item.price * 1.1).floor %></td>
            <td><%= order_detail.amount %></td>
            <td><%= ((order_detail.item.price * 1.1).floor * order_detail.amount) %></td>
            <td><%= order_detail.production_status_i18n %></td>
            <% @sum += ((order_detail.item.price * 1.1).floor * order_detail.amount) %>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-4">
      <table>
        <tr>
          <th>商品合計</th>
          <td><%= @sum %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.postage %>円</td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <th><%= @sum + @order.postage %>円</th>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<h1>About</h1>
<p>
  ながのCAKEは全国発送可能なケーキ屋さんです。<br/>
  お子様からお年寄の方までお召し上がりいただけるよう、<br/>
  様々なバリエーションをご用意しております。<br/>
  また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。<br>
  ぜひご注文ください。
</p>