config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  get "/about" => "public/homes#about"

  #管理者用
  #URL/admin/sign_in
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    get "/" => "homes#top"
    patch "/admin/order_details/:id" => "order_details#update", as: "order_details"
  end

  #顧客用
  #URL/customers/sign_in
  scope module: :public do
    resource :customers, only: [:show, :edit, :update]
    delete "/cart_items/empty" => "cart_items#empty", as: "empty"
    post "orders/confirm" => "orders#confirm", as: "confirm"
    get "orders/complete" => "orders#complete",as: "complete"
    get "/customers/unsubscribe" => "customers#unsubscribe", as: "unsubscribe"
    patch "/customers/withdrawal" => "customers#withdrawal", as: "withdrawal"
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :create, :index, :show]
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
    "〒" + postal_code + '' + address + '' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

   #小計
  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders

  def name
    self.last_name + "" + self.first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_detaios, dependent: :destroy

  def get_image
    image
  end
     #税込価格
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {
    credit: 0,
    bank: 1,
  }

  enum status: {
    payment_waiting: 0,
    payment_confirmation: 1,
    in_production: 2,
    preparing_delivery: 3,
    delivered: 4,
  }

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  def postage
    800
  end

  def with_tax_price
    (price * 1.1).floor
  end

  def subtotal
    item.with_tax_price * amount
  end


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum production_status: {
    no_production: 0,
    production_waiting: 1,
    in_production: 2,
    completed: 3,
  }

  belongs_to :order
  belongs_to :item
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
    @item_sum = 0
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    @item.save
    p @item.errors.full_messages
    redirect_to admin_item_path(@item.id)
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
    @genre = @item.genre
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @genres = Genre.all
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <!--nagano_cakeのロゴが入る-->
          <a class="navbar-brand" href="/"><%= image_tag "nagano_cake_logo.jpg", size: "75x75" %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "商品一覧", admin_items_path, class: 'btn btn-outline-secondary p-2 m-3'  %>
              </li>

              <li class="nav-item">
                <%= link_to "会員一覧", admin_customers_path, class: 'btn btn-outline-secondary p-2 m-3' %>
              </li>

              <li>
                <%= link_to "注文履歴一覧", admin_path, class: 'btn btn-outline-secondary p-2 m-3' %>
              </li>

              <li class="nav-item">
                <%= link_to "ジャンル一覧", admin_genres_path, class: 'btn btn-outline-secondary p-2 m-3' %>
              </li>

              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-outline-secondary p-2 m-3' %>
              </li>

              <% elsif customer_signed_in? %>
              <li>
                <%= link_to "マイページ", customers_path, class: "btn btn-outline-secondary p-2 m-3" %>
              </li>

              <li>
                <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary p-2 m-3" %>
              </li>

              <li>
                <%= link_to "カート", cart_items_path, class: "btn btn-outline-secondary p-2 m-3" %>
              </li>

              <li>
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-outline-secondary p-2 m-3' %>
              </li>

              <% else %>
              <li class="nav-item">
                <%= link_to "About", about_path, class: 'btn btn-outline-secondary p-2 m-3' %>
              </li>

              <li class="nav-item">
                <%= link_to "商品一覧", items_path, class: 'btn btn-outline-secondary p-2 m-3' %>
              </li>

              <li class="nav-item">
                <%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-outline-secondary p-2 m-3' %>
              </li>

              <li class="nav-item">
                <%= link_to "ログイン", new_customer_session_path, class: 'btn btn-outline-secondary p-2 m-3' %>
              </li>
              <% end %>
            </ul>
          </div>
          </div>
        </div>
      </nav>

    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-light text-white pt-5 pb-4">

    </footer>
  </body>
</html>